config: conf/train.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/tts_train_raw_phn_g2pk
ngpu: 1
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: 4
dist_rank: 0
local_rank: 0
dist_master_addr: localhost
dist_master_port: 51057
dist_launcher: null
multiprocessing_distributed: true
unused_parameters: false
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 500
patience: null
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - loss
    - min
-   - train
    - loss
    - min
keep_nbest_models: 5
nbest_averaging_interval: 0
grad_clip: 10.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: null
use_matplotlib: true
use_tensorboard: true
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: 1000
batch_size: 64
valid_batch_size: null
batch_bins: 1000000
valid_batch_bins: null
train_shape_file:
- exp/tts_stats_raw_phn_g2pk/train/text_shape.phn
- exp/tts_stats_raw_phn_g2pk/train/speech_shape
valid_shape_file:
- exp/tts_stats_raw_phn_g2pk/valid/text_shape.phn
- exp/tts_stats_raw_phn_g2pk/valid/speech_shape
batch_type: unsorted
valid_batch_type: null
fold_length:
- 150
- 204800
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/raw/tr_no_dev/text
    - text
    - text
-   - dump/raw/tr_no_dev/wav.scp
    - speech
    - sound
-   - dump/raw/tr_no_dev/utt2sid
    - sids
    - text_int
-   - dump/raw/tr_no_dev/utt2lid
    - lids
    - text_int
valid_data_path_and_name_and_type:
-   - dump/raw/dev/text
    - text
    - text
-   - dump/raw/dev/wav.scp
    - speech
    - sound
-   - dump/raw/dev/utt2sid
    - sids
    - text_int
-   - dump/raw/dev/utt2lid
    - lids
    - text_int
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 1.0
scheduler: noamlr
scheduler_conf:
    model_size: 384
    warmup_steps: 4000
token_list:
- <blank>
- <unk>
- ''
- ᅡ
- ᅵ
- ᅳ
- ᄀ
- ᄋ
- ᄂ
- ᅥ
- ᆫ
- ᄅ
- ᅩ
- ᄉ
- ᆯ
- ᄃ
- ᄆ
- ᄌ
- ᅮ
- ᄒ
- ᆼ
- ᅦ
- ᅢ
- ᄇ
- ᅧ
- .
- ᆮ
- ᄄ
- ᆷ
- ᄁ
- ᄊ
- ᄎ
- ','
- ᄏ
- ᅴ
- ᄑ
- ᄐ
- ᆨ
- ᅪ
- ᄍ
- ᆸ
- ᅭ
- ᅣ
- ᅬ
- ᅱ
- ᄈ
- ᅯ
- '!'
- '?'
- ᅨ
- ᅲ
- ᅫ
- ᅤ
- ᅰ
- …
- '~'
- ·
- '"'
- <sos/eos>
odim: null
model_conf: {}
use_preprocessor: true
token_type: phn
bpemodel: null
non_linguistic_symbols: null
cleaner: null
g2p: g2pk
feats_extract: fbank
feats_extract_conf:
    n_fft: 1024
    hop_length: 256
    win_length: null
    fs: 22050
    fmin: 80
    fmax: 7600
    n_mels: 80
normalize: global_mvn
normalize_conf:
    stats_file: exp/tts_stats_raw_phn_g2pk/train/feats_stats.npz
tts: fastspeech3
tts_conf:
    spks: 27
    langs: 8
    adim: 384
    aheads: 2
    elayers: 4
    eunits: 1536
    dlayers: 4
    dunits: 1536
    positionwise_layer_type: conv1d
    positionwise_conv_kernel_size: 3
    duration_predictor_layers: 2
    duration_predictor_chans: 256
    duration_predictor_kernel_size: 3
    postnet_layers: 5
    postnet_filts: 5
    postnet_chans: 256
    use_masking: true
    encoder_normalize_before: true
    decoder_normalize_before: true
    reduction_factor: 1
    encoder_type: conformer
    decoder_type: conformer
    conformer_rel_pos_type: latest
    conformer_pos_enc_layer_type: rel_pos
    conformer_self_attn_layer_type: rel_selfattn
    conformer_activation_type: swish
    use_macaron_style_in_conformer: true
    use_cnn_in_conformer: true
    conformer_enc_kernel_size: 7
    conformer_dec_kernel_size: 31
    init_type: xavier_uniform
    transformer_enc_dropout_rate: 0.2
    transformer_enc_positional_dropout_rate: 0.2
    transformer_enc_attn_dropout_rate: 0.2
    transformer_dec_dropout_rate: 0.2
    transformer_dec_positional_dropout_rate: 0.2
    transformer_dec_attn_dropout_rate: 0.2
    pitch_predictor_layers: 5
    pitch_predictor_chans: 256
    pitch_predictor_kernel_size: 5
    pitch_predictor_dropout: 0.5
    pitch_embed_kernel_size: 1
    pitch_embed_dropout: 0.0
    stop_gradient_from_pitch_predictor: true
    energy_predictor_layers: 2
    energy_predictor_chans: 256
    energy_predictor_kernel_size: 3
    energy_predictor_dropout: 0.5
    energy_embed_kernel_size: 1
    energy_embed_dropout: 0.0
    stop_gradient_from_energy_predictor: false
pitch_extract: dio
pitch_extract_conf:
    fs: 22050
    n_fft: 1024
    hop_length: 256
    f0max: 600
    f0min: 50
    reduction_factor: 1
pitch_normalize: global_mvn
pitch_normalize_conf:
    stats_file: exp/tts_stats_raw_phn_g2pk/train/pitch_stats.npz
energy_extract: energy
energy_extract_conf:
    fs: 22050
    n_fft: 1024
    hop_length: 256
    win_length: null
    reduction_factor: 1
energy_normalize: global_mvn
energy_normalize_conf:
    stats_file: exp/tts_stats_raw_phn_g2pk/train/energy_stats.npz
required:
- output_dir
- token_list
version: 0.10.5a1
distributed: true
